version: "2"
run:
  issues-exit-code: 1
  tests: true
  build-tags:
   - arcadia
  modules-download-mode: vendor
  allow-parallel-runners: false
  go: ""
linters:
  # Default set of linters.
  # The value can be: `standard`, `all`, `none`, or `fast`.
  # Default: standard
  # Compile protos beforehand
  # TODO CGO_CFLAGS=-I<FULL PATH TO REPO>nbs/contrib/libs/zstd/include ~/go/bin/golangci-lint run cloud/...
  default: all
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - canonicalheader
    - containedctx
    - copyloopvar
    - dogsled
    - dupword
    - durationcheck
    - err113
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - exhaustruct
    - exptostd
    - fatcontext
    - forbidigo
    - forcetypeassert
    - funcorder
    - funlen
    - gocheckcompilerdirectives
    - gochecknoglobals
    - gochecknoinits
    - gochecksumtype
    - goconst
    - gocritic
    - godot
    - goheader
    - gomoddirectives
    - goprintffuncname
    - gosec
    - gosmopolitan
    - govet
    - grouper
    - inamedparam
    - ineffassign
    - interfacebloat
    - intrange
    - ireturn
    - lll
    - loggercheck
    - maintidx
    - makezero
    - mirror
    - misspell
    - mnd
    - musttag
    - nakedret
    - nestif
    - nilerr
    - nilnesserr
    - nilnil
    - noctx
    - nonamedreturns
    - nosprintfhostport
    - perfsprint
    - prealloc
    - predeclared
    - protogetter
    - reassign
    - recvcheck
    - revive
    - rowserrcheck
    - sloglint
    - spancheck
    - sqlclosecheck
    - staticcheck
    - tagalign
    - tagliatelle
    - testableexamples
    - testifylint
    - thelper
    - tparallel
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - usetesting
    - varnamelen
    - wastedassign
  disable:
    - contextcheck
    - cyclop
    - decorder
    - depguard
    - dupl
    - exhaustive
    - ginkgolinter
    - gocognit
    - gocyclo
    - godox
    - gomodguard
    - grouper
    - iface
    - importas
    - nlreturn
    - nolintlint
    - paralleltest
    - promlinter
    - testpackage
    - whitespace
    - wrapcheck
    - wsl
    - zerologlint
  settings:
    lll:
      line-length: 80
    tagliatelle:
      case:
        rules:
          json: camel
    testifylint:
      enable-all: true
    whitespace:
      multi-func: true
formatters:
  enable:
    # Do not work for now
    - gci
    - gofmt
    - gofumpt
    - goimports
    - golines
output:
  formats:
    html:
      path: "golangci-lint-report.html"
