apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-pv
spec:
  volumeMode: Filesystem
  capacity:
    storage: 1Gi
  accessModes:
   - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: csi-nbs
  claimRef:
    namespace: nbs-csi-driver
    name: my-pvc
  csi:
    driver: nbs.csi.nebius.ai
    volumeHandle: my-nbs-volume-id
    volumeAttributes:
      key1: value1
      key2: value2