apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.names.configname" . }}
data:
  {{ include "disk-manager.clientConfigName" . }}: |
{{ include "disk-manager.clientConfigFile" . | indent 4 }}
  {{ include "disk-manager.serverConfigName" . }}: |
{{ include "disk-manager.serverConfigFile" . | indent 4 }}