apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "common.names.fullname" . }}
  labels:
    app: {{ include "common.names.fullname" . }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
  annotations:
    checksum/client-config: {{ include "disk-manager.clientConfigFile" . | sha256sum }}
    checksum/server-config: {{ include "disk-manager.serverConfigFile" . | sha256sum }}
spec:
  selector:
    matchLabels:
      app: {{ include "common.names.fullname" . }}
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ include "common.names.fullname" . }}
    spec:
      volumes:
      - name: {{ include "disk-manager.serverVolumeName" . }}
        configMap:
          name: {{ include "common.names.configname" . }}
          items:
            - key: {{ include "disk-manager.serverConfigName" . }}
              path: {{ include "disk-manager.serverConfigName" . }}
      - name: {{ include "disk-manager.clientVolumeName" . }}
        configMap:
          name: {{ include "common.names.configname" . }}
          items:
            - key: {{ include "disk-manager.clientConfigName" . }}
              path: {{ include "disk-manager.clientConfigName" . }}
      initContainers:
      - name: disk-manager-init
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: "{{ .Values.image.pullPolicy }}"
        command: ["/usr/bin/yc-disk-manager-init-db", '--config={{ include "disk-manager.serverConfigPath" . }}']
        volumeMounts:
          - name: {{ include "disk-manager.serverVolumeName" . }}
            mountPath: {{ include "disk-manager.serverConfigPath" . }}
            subPath: {{ include "disk-manager.serverConfigName" . }}

      containers:
      - name: disk-manager
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        command: ["/usr/bin/yc-disk-manager", '--config={{ include "disk-manager.serverConfigPath" . }}']
        imagePullPolicy: "{{ .Values.image.pullPolicy }}"
        volumeMounts:
        - name: {{ include "disk-manager.serverVolumeName" . }}
          mountPath: {{ include "disk-manager.serverConfigPath" . }}
          subPath: {{ include "disk-manager.serverConfigName" . }}
        {{- if eq .Values.serviceKind "controlplane" }}
        - name: {{ include "disk-manager.clientVolumeName" . }}
          mountPath: {{ include "disk-manager.clientConfigPath" . }}
          subPath: {{ include "disk-manager.clientConfigName" . }}
        {{- end }}
        ports:
          - containerPort: {{ .Values.service.internalPort }}