apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-all-{{ .Values.serviceKind }}
spec:
  podSelector:
    matchLabels:
      app: {{ include "common.names.fullname" }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - {}
  egress:
    - {}