apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-all-{{ .Values.serviceKind }}
spec:
  podSelector:
    matchLabels: {{ $fullname := printf "%s-%s" "disk-manager" .Values.serviceKind }}
      app: {{ $fullname }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - {}
  egress:
    - {}